# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeDetectServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='blink',
            field=models.IntegerField(default=1),
        ),
    ]
