# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeDetectServer', '0002_record_blink'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='EAR',
            field=models.FloatField(default=0),
        ),
    ]
