# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeDetectServer', '0003_record_ear'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='record',
            name='threshold',
            field=models.FloatField(default=-1),
        ),
    ]
