# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeDetectServer', '0005_auto_20170515_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.CharField(default='hgod', max_length=30),
        ),
    ]
